### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by otakuto** [TaiseiIto/Assignment#2]
ライセンスの指定をお願いします.

**Comment by t-kazu** [comment]
MIT Licenseが良く見かけるライセンスですが、この場合ライブラリみたいな扱いではないですしちょっとどのライセンスが良いか悩む感じですね。

**Comment by TaiseiIto** [comment]
ライセンスとか気にしたこともなかったです。

**Comment by otakuto** [comment]
レポートとしての再利用を考えるとMITライセンスが扱いやすいと思います。

**Comment by TaiseiIto** [comment]
ありがとうございます。
とりあえず
https://opensource.org/licenses/mit-license.php
を読んでみてよさそうだったらMITにします。

**Comment by TaiseiIto** [comment]
MITにしました。

**Comment by t-kazu** [comment]
ライセンスついてよかったです。

**Comment by TaiseiIto** [comment]
クローズしますね。
